CMS/Models/DbConnection.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CMS.Models
{
    public class DbConnection
    {
        public string MainconnectionString = "Data Source=172.16.0.78;Initial Catalog=HIS_PRO;User ID=sa;Password=AiHWH@123";
    }
}

CMS/Models/EmployeeDAL.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace CMS.Models
{
    public class EmployeeDAL
    {
        private DbConnection ConnStr = new DbConnection();

        //Get All
        public IEnumerable<EmployeeListViewModel> GetAllEmployees()
        {
            List<EmployeeListViewModel> empList = new List<EmployeeListViewModel>();

            using (SqlConnection conn = new SqlConnection(ConnStr.MainconnectionString))
            {
                SqlCommand cmd = new SqlCommand("get_list_employee", conn);
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                conn.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    EmployeeListViewModel emp = new EmployeeListViewModel();
                    emp.employee_nr = dr["employee_nr"].ToString();
                    emp.name_l = dr["name_l"].ToString();
                    emp.sex_rcd = dr["sex_rcd"].ToString();
                    emp.phone_number = dr["phone_number"].ToString();
                    emp.email_business = dr["email_business"].ToString();
                    empList.Add(emp);
                }
                conn.Close();
            }
            return empList;
        }
    }
}

CMS/Models/EmployeeListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CMS.Models
{
    public class EmployeeListViewModel
    {
        public string employee_nr { get; set; }
        public string name_l { get; set; }
        public string sex_rcd { get; set; }
        public string phone_number { get; set; }
        public string email_business { get; set; }
        public string emp_status_name_e { get; set; }
    }
}

CMS/Models/EmployeeStatusVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CMS.Models
{
    public class EmployeeStatusVm
    {
        public string employee_status_rcd { get; set; }
        public string emp_status_name_e { get; set; }
    }
}

CMS/Models/EmployeeVm.cs
using System;

namespace CMS.Models
{
    public class EmployeeVm
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string Office { get; set; }
        public int Age { get; set; }
        public DateTime Start_date { get; set; }
        public Decimal Salary { get; set; }
    }
}

CMS/Models/ErrorViewModel.cs
using System;

namespace CMS.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CMS/Models/GetPagingRequest.cs
namespace CMS.Models
{
    public class GetPagingRequest : PagingRequestBase
    {
        public string Keyword { get; set; }
        public string Status { get; set; }
    }
}

CMS/Models/PagedResult.cs
using System.Collections.Generic;

namespace CMS.Models
{
    public class PagedResult<T> : PagingResultBase
    {
        public IEnumerable<T> Items { set; get; }
    }
}

CMS/Models/PagingRequestBase.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CMS.Models
{
    public class PagingRequestBase
    {
        public int pageIndex { get; set; }
        public int pageSize { get; set; }
    }
}

CMS/Models/PagingResultBase.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CMS.Models
{
    public class PagingResultBase
    {
        public int PageIndex { get; set; }

        public int PageSize { get; set; }

        public int TotalRows { get; set; }

        public int TotalPages
        {
            get
            {
                var pageCount = (double)TotalRows / PageSize;
                return (int)Math.Ceiling(pageCount);
            }
        }
    }
}

CMS/Controllers/Components/PagerViewComponent.cs
using CMS.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CMS.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagingResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

CMS/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CMS.Models;
using CMS.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CMS.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeRepository _employeeRepository;

        public EmployeeController(IEmployeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }

        public async Task<IActionResult> Index(string keyword, string status, int pageIndex = 1, int pageSize = 10)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            else
            {
                var request = new GetPagingRequest()
                {
                    Keyword = keyword,
                    Status = status,
                    pageIndex = pageIndex,
                    pageSize = pageSize
                };
                var result = await _employeeRepository.GetEmployee(request);
                ViewBag.Keyword = keyword;

                return View(result);
            }
        }
    }
}

CMS/Controllers/HomeController.cs
using CMS.Models;
using CMS.Repository;
using CMS.Utilities;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;

namespace CMS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public HomeController(ILogger<HomeController> logger,
            IEmployeeRepository employeeRepository,
            IWebHostEnvironment hostingEnvironment
            )
        {
            _logger = logger;
            _employeeRepository = employeeRepository;
            _hostingEnvironment = hostingEnvironment;
        }

        public async Task<IActionResult> Index(string frDate, string toDate)
        {
            var data = await _employeeRepository.GetEmployeeAll(frDate, toDate);
            ViewBag.fDate = frDate;
            ViewBag.tDate = toDate;
            return View(data);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public async Task<IActionResult> ExportExcel(string frDate, string toDate)
        {
            string sWebRootFolder = _hostingEnvironment.WebRootPath;
            string directory = Path.Combine(sWebRootFolder, "export-files");
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }
            string sFileName = $"Employee_{DateTime.Now:yyyyMMddhhmmss}.xlsx";
            string fileUrl = $"{Request.Scheme}://{Request.Host}/export-files/{sFileName}";
            FileInfo file = new FileInfo(Path.Combine(directory, sFileName));
            if (file.Exists)
            {
                file.Delete();
                file = new FileInfo(Path.Combine(sWebRootFolder, sFileName));
            }
            var products = await _employeeRepository.GetEmployeeAll(frDate, toDate);
            try
            {
                await ReportHelper.GenerateXls(products, file);

                return new OkObjectResult(fileUrl);
            }
            catch (Exception)
            {
                return new NoContentResult();
            }
        }
    }
}

CMS/Views/Employee/Index.cshtml
@using CMS.Models;
@model PagedResult<EmployeeListViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Container fluid  -->
<!-- ============================================================== -->
<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">Employee</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                    <li class="breadcrumb-item active">Employee</li>
                </ol>
                <button type="button" class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> Create New</button>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Info box -->
    <!-- ============================================================== -->
    <!-- /row -->
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6 col-xs-12">
                            @*<a class="btn btn-info btn-rounded m-t-10" asp-action="Create" asp-controller="Employee">Tạo mới</a>*@
                            <button type="button" class="btn btn-info btn-rounded m-t-10" data-toggle="modal" data-target="#add-contact">Add New Contact</button>
                        </div>
                        <div class="col-md-6 col-xs-12">
                            <form asp-action="Index" method="get">
                                <div class="row">
                                    <div class="col-md-4">
                                        <input type="text" value="@ViewBag.Keyword" name="keyword" class="form-control" />
                                    </div>
                                    @*<div class="col-md-4">
                                            <select name="status" onchange="this.form.submit()" asp-items="@ViewBag.Status" class="form-control">
                                                <option>-- Chọn danh mục--</option>
                                            </select>
                                        </div>*@
                                    <div class="cold-md-3">
                                        <button type="submit" class="btn btn-primary">Tìm</button>
                                        <button type="button" onclick="window.location.href='/Employee'" class="btn btn-dark">Reset</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @*<div class="right-page-header">
                            <div class="d-flex">
                                <div class="align-self-center">
                                    <h4 class="card-title m-t-10">Contacts / Employee List </h4>
                                </div>
                                <form asp-action="Index" method="get">
                                    <div class="ml-auto">
                                        <input type="text" value="@ViewBag.Keyword" name="keyword" id="demo-input-search2" placeholder="search contacts" class="form-control">
                                    </div>
                                </form>
                            </div>
                        </div>
                        <button type="button" class="btn btn-info btn-rounded m-t-10 float-right" data-toggle="modal" data-target="#add-contact">Add New Contact</button>*@
                    <!-- Add Contact Popup Model -->
                    <div id="add-contact" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                    <h4 class="modal-title" id="myModalLabel">Add New Contact</h4>
                                </div>
                                <div class="modal-body">
                                    <from class="form-horizontal form-material">
                                        <div class="form-group">
                                            <div class="col-md-12 m-b-20">
                                                <input type="text" class="form-control" placeholder="Type name">
                                            </div>
                                            <div class="col-md-12 m-b-20">
                                                <input type="text" class="form-control" placeholder="Email">
                                            </div>
                                            <div class="col-md-12 m-b-20">
                                                <input type="text" class="form-control" placeholder="Phone">
                                            </div>
                                            <div class="col-md-12 m-b-20">
                                                <input type="text" class="form-control" placeholder="Designation">
                                            </div>
                                            <div class="col-md-12 m-b-20">
                                                <input type="text" class="form-control" placeholder="Age">
                                            </div>
                                            <div class="col-md-12 m-b-20">
                                                <input type="text" class="form-control" placeholder="Date of joining">
                                            </div>
                                            <div class="col-md-12 m-b-20">
                                                <input type="text" class="form-control" placeholder="Salary">
                                            </div>
                                            <div class="col-md-12 m-b-20">
                                                <div class="fileupload btn btn-danger btn-rounded waves-effect waves-light">
                                                    <span><i class="ion-upload m-r-5"></i>Upload Contact Image</span>
                                                    <input type="file" class="upload">
                                                </div>
                                            </div>
                                        </div>
                                    </from>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-info waves-effect" data-dismiss="modal">Save</button>
                                    <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancel</button>
                                </div>
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                    <div class="table-responsive">
                        <table id="demo-foo-addrow" class="table table-bordered m-t-30 table-hover contact-list" data-paging="true" data-paging-size="7">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Gender</th>
                                    <th>Phone</th>
                                    <th>Email</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Items)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.employee_nr)
                                        </td>
                                        <td>
                                            <a href="javascript:void(0)">
                                                <img src="images/users/4.jpg" alt="user" width="40" class="img-circle" />
                                                @Html.DisplayFor(modelItem => item.name_l)
                                            </a>
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.sex_rcd)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.phone_number)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.email_business)
                                        </td>
                                        <td>
                                            @if (item.emp_status_name_e == "Active")
                                            {
                                                <span class="label label-success">
                                                    @Html.DisplayFor(modelItem => item.emp_status_name_e)
                                                </span>
                                            }
                                            else if (item.emp_status_name_e == "Inactive")
                                            {
                                                <span class="label label-danger">
                                                    @Html.DisplayFor(modelItem => item.emp_status_name_e)
                                                </span>
                                            }
                                            else if (item.emp_status_name_e == "Indefinite term")
                                            {
                                                <span class="label label-warning">
                                                    @Html.DisplayFor(modelItem => item.emp_status_name_e)
                                                </span>
                                            }
                                            else
                                            {
                                                <span class="label label-info">
                                                    @Html.DisplayFor(modelItem => item.emp_status_name_e)
                                                </span>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    @await Component.InvokeAsync("Pager", Model)
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
    <!-- ============================================================== -->
    <!-- End Page Content -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Right sidebar -->
    <!-- ============================================================== -->
    <!-- .right-sidebar -->
    <!-- ============================================================== -->
    <!-- End Right sidebar -->
    <!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- End Container fluid  -->

CMS/Views/Home/Index.cshtml
@using CMS.Models;
@model IEnumerable<EmployeeListViewModel>
@{
    ViewData["Title"] = "AIH";
}

<!-- Container fluid  -->
<!-- ============================================================== -->
<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">Dashboard</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                    <li class="breadcrumb-item active">Dashboard</li>
                </ol>
                <button type="button" class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> Create New</button>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Info box -->
    <!-- ============================================================== -->
    <!-- /row -->
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <form asp-action="Index" method="get" id="formMain">
                        <div class="row show-grid">
                            <div class="col-xs-6 col-sm-4 col-lg-3 col-xl-2">
                                <div class="form-group">
                                    <input type="date" value="@ViewBag.fDate" name="frDate" id="frDate" class="form-control">
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-4 col-lg-3 col-xl-2">
                                <div class="form-group">
                                    <input type="date" value="@ViewBag.tDate" name="toDate" id="toDate" class="form-control">
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-4 col-lg-3 col-xl-2">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary">Filter</button>
                                    <button class="btn btn-success" id="btn-export" type="button">Export</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card-body">
                    <div class="table-responsive m-t-40">
                        <table id="allemployee" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Gender</th>
                                    <th>Phone</th>
                                    <th>Email</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.employee_nr)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.name_l)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.sex_rcd)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.phone_number)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.email_business)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.emp_status_name_e)
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
    <!-- ============================================================== -->
    <!-- End Page Content -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Right sidebar -->
    <!-- ============================================================== -->
    <!-- .right-sidebar -->
    <!-- ============================================================== -->
    <!-- End Right sidebar -->
    <!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- End Container fluid  -->
@section Scripts{
    <script>
        $(document).ready(function () {
            $('#allemployee').DataTable({
                "pagingType": "full_numbers"
            });
            var date = new Date();

            var day = date.getDate();
            var month = date.getMonth() + 1;
            var year = date.getFullYear();

            if (month < 10) month = "0" + month;
            if (day < 10) day = "0" + day;

            var frDate = year - 1 + "-" + month + "-" + day;
            var toDate = year + "-" + month + "-" + day;

            if ($('#frDate').val().length == 0)
                $('#frDate').val(frDate);

            if ($('#toDate').val().length == 0)
                $('#toDate').val(toDate);            
        });
        $('#btn-export').on('click', function () {
            $.ajax({
                type: "POST",
                url: "/Home/ExportExcel",
                data: {
                    frDate: $('#frDate').val(),
                    toDate: $('#toDate').val()
                },
                beforeSend: function () {
                    //tedu.startLoading();
                },
                success: function (response) {
                    window.location.href = response;
                    //tedu.notify('success progress', 'success');
                    //tedu.stopLoading();
                },
                error: function () {
                    //tedu.notify('Has an error in progress', 'error');
                    //tedu.stopLoading();
                }
            });
        });
    </script>
}

CMS/Views/Shared/Components/Pager/Default.cshtml
@using CMS.Models
@model PagingResultBase

@{
    var urlTemplate = Url.Action() + "?pageIndex={0}";
    var request = ViewContext.HttpContext.Request;
    foreach (var key in request.Query.Keys)
    {
        if (key == "pageIndex")
        {
            continue;
        }
        if (request.Query[key].Count > 1)
        {
            foreach (var item in (string[])request.Query[key])
            {
                urlTemplate += "&" + key + "=" + item;
            }
        }
        else
        {
            urlTemplate += "&" + key + "=" + request.Query[key];
        }
    }
    var startIndex = Math.Max(Model.PageIndex - 5, 1);
    var finishIndex = Math.Min(Model.PageIndex + 5, Model.TotalPages);
}

@if (Model.TotalPages > 1)
{
    <ul class="pagination">
        @if (Model.PageIndex != startIndex)
        {
            <li class="page-item">
                <a class="page-link" title="1" href="@urlTemplate.Replace("{0}","1")">&laquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="@urlTemplate.Replace("{0}", (Model.PageIndex-1).ToString())">&lsaquo;</a>
            </li>
        }

        @for (var i = startIndex; i <= finishIndex; i++)
        {
            if (i == Model.PageIndex)
            {
                <li class="page-item active">
                    <a class="page-link" href="#">@i <span class="sr-only">(current)</span></a>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link" title="Page @i.ToString()" href="@urlTemplate.Replace("{0}", i.ToString())">@i</a>
                </li>
            }
        }

        @if (Model.PageIndex != finishIndex)
        {
            <li class="page-item">
                <a class="page-link" title="@Model.TotalPages.ToString()" href="@urlTemplate.Replace("{0}", (Model.PageIndex+1).ToString())">&rsaquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="@urlTemplate.Replace("{0}", Model.TotalPages.ToString())">&raquo;</a>
            </li>
        }
    </ul>
}